#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Build atopic-dermatitis-comorbidity.html from cloned template."""
import re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

P = r'C:\Users\User\Desktop\翊嘉\程式\個人網頁\DermNotes\blog\atopic-dermatitis-comorbidity.html'
with open(P, 'r', encoding='utf-8') as f:
    s = f.read()

OLD_SLUG = 'eczema-myths'
NEW_SLUG = 'atopic-dermatitis-comorbidity'
TITLE_ZH = '異位性皮膚炎共病完整評估 — 氣喘、過敏、心理、骨骼、心血管(AAD 2022 + 2026 整合)'
DESC_ZH = ('成人與兒童異位性皮膚炎共病完整對照:氣喘 / 食物過敏 / 過敏性鼻炎 / 嗜酸性食道炎 / 圓禿 / '
           '蕁麻疹 / 憂鬱 / 焦慮 / 骨質疏鬆 / 心血管疾病 / 代謝症候群 / 皮膚感染。整合 AAD 2022 (成人 32 條) + Sidbury 2026 (兒童 29 條) JAAD 共識。')

s = re.sub(r'<title>[^<]*</title>', f'<title>{TITLE_ZH} | ChenDermatologist · 陳翊嘉醫師</title>', s, count=1)
s = re.sub(r'<meta name="description" content="[^"]*"', f'<meta name="description" content="{DESC_ZH}"', s, count=1)
s = s.replace(f'/blog/{OLD_SLUG}', f'/blog/{NEW_SLUG}').replace(f'/en/blog/{OLD_SLUG}', f'/en/blog/{NEW_SLUG}')
s = re.sub(r'<meta property="og:title" content="[^"]*"', f'<meta property="og:title" content="{TITLE_ZH} | ChenDermatologist"', s, count=1)
s = re.sub(r'<meta property="og:description" content="[^"]*"', f'<meta property="og:description" content="陳翊嘉醫師整理 AAD 2022 異膚共病 32 條 + Sidbury 2026 兒童 29 條共病聲明。"', s, count=1)
s = re.sub(r'<meta property="og:image" content="[^"]*"', f'<meta property="og:image" content="https://chendermatologist.com/assets/og/{NEW_SLUG}.png"', s, count=1)
s = re.sub(r'<meta name="twitter:title" content="[^"]*"', f'<meta name="twitter:title" content="{TITLE_ZH} | ChenDermatologist"', s, count=1)
s = re.sub(r'<meta name="twitter:description" content="[^"]*"', f'<meta name="twitter:description" content="氣喘/過敏/憂鬱/骨質/心血管 — AAD 2022 + 2026 整合"', s, count=1)
s = re.sub(r'<meta name="twitter:image" content="[^"]*"', f'<meta name="twitter:image" content="https://chendermatologist.com/assets/og/{NEW_SLUG}.png"', s, count=1)

NEW_LD = '''<script type="application/ld+json">{"@context":"https://schema.org","@type":"MedicalScholarlyArticle","headline":"異位性皮膚炎共病完整評估","description":"成人與兒童異膚共病:氣喘、過敏、心理、骨骼、心血管、感染。","datePublished":"2026-05-14","dateModified":"2026-05-14","inLanguage":"zh-Hant-TW","author":{"@type":"Person","name":"陳翊嘉 醫師","alternateName":"Yi-Jia Chen, MD","url":"https://chendermatologist.com/about"},"publisher":{"@type":"Person","name":"陳翊嘉 醫師","url":"https://chendermatologist.com/"},"mainEntityOfPage":"https://chendermatologist.com/blog/atopic-dermatitis-comorbidity","image":"https://chendermatologist.com/assets/og/atopic-dermatitis-comorbidity.png","about":[{"@type":"MedicalCondition","name":"Atopic dermatitis","alternateName":"異位性皮膚炎"}],"citation":[{"@type":"CreativeWork","name":"Davis et al. AAD Guidelines: Awareness of comorbidities associated with atopic dermatitis in adults","url":"https://doi.org/10.1016/j.jaad.2022.01.009","datePublished":"2022-06"},{"@type":"CreativeWork","name":"Sidbury et al. Guidelines of care for the primary prevention of atopic dermatitis and awareness of comorbid conditions in pediatric atopic dermatitis","datePublished":"2026"}]}</script><script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"首頁","item":"https://chendermatologist.com/"},{"@type":"ListItem","position":2,"name":"衛教文章","item":"https://chendermatologist.com/blog/"},{"@type":"ListItem","position":3,"name":"異位性皮膚炎共病評估","item":"https://chendermatologist.com/blog/atopic-dermatitis-comorbidity"}]}</script>'''
s = re.sub(r'(<script type="application/ld\+json">[\s\S]*?</script>\s*)+', NEW_LD, s, count=1)

ART = '''<article class="max-w-3xl mx-auto px-5 sm:px-8 my-8 prose prose-lg" data-slug="atopic-dermatitis-comorbidity"><nav class="text-[12.5px] text-ink-500 mb-3" aria-label="breadcrumb"><a href="/" class="hover:text-teal-700">首頁</a> · <a href="/blog/" class="hover:text-teal-700">衛教文章</a> · <span class="text-ink-700" data-zh="異膚共病評估" data-en="AD Comorbidity Evaluation">異膚共病評估</span></nav><div class="text-[11px] uppercase tracking-[.22em] text-teal-700 font-semibold mb-2" data-zh="異膚 · 共病" data-en="Atopic Dermatitis · Comorbidities">異膚 · 共病</div><h1 class="font-display font-bold text-[28px] sm:text-[36px] leading-tight text-ink-900 mb-3" data-zh="異位性皮膚炎共病完整評估 — 氣喘、過敏、心理、骨骼、心血管" data-en="Atopic Dermatitis Comorbidity Evaluation — Asthma, Allergy, Mental Health, Bone, CV">異位性皮膚炎共病完整評估 — 氣喘、過敏、心理、骨骼、心血管</h1><div class="text-[13.5px] text-ink-500 mb-6" data-zh="陳翊嘉 醫師 · 整合 Davis 2022 (成人 32 statements) + Sidbury 2026 (兒童 29 statements) JAAD · 更新 2026-05-14" data-en="Dr. Yi-Jia Chen · Integrating Davis 2022 (adult 32 statements) + Sidbury 2026 (pediatric 29 statements) JAAD · Updated 2026-05-14">陳翊嘉 醫師 · 整合 Davis 2022 (成人 32 statements) + Sidbury 2026 (兒童 29 statements) JAAD · 更新 2026-05-14</div>

<div class="dn-tldr" style="background:#fefce8;border-left:4px solid #ca8a04;border-radius:0 10px 10px 0;padding:14px 18px;margin:18px 0;font-size:14px;line-height:1.85"><strong data-zh="一句話結論" data-en="TL;DR">一句話結論</strong>:<span data-zh="異膚不只是皮膚病。AAD 2022 + 2026 共識整理出 5 大類共病:過敏(氣喘 / 食物 / 鼻炎 / EoE)、心理(憂鬱 / 焦慮 / 自殺意念)、骨骼(骨質疏鬆 / 骨折)、心血管(輕度上升)、皮膚感染(金黃色葡萄球菌 / eczema herpeticum)。Dupilumab 等新藥同時治多病、改變了治療策略。" data-en="AD is more than skin disease. AAD 2022 + 2026 consensus identifies 5 major comorbidity categories: atopic (asthma / food allergy / rhinitis / EoE), mental health (depression / anxiety / suicidal ideation), bone (osteoporosis / fracture), cardiovascular (mildly increased), skin infection (S aureus / eczema herpeticum). Dupilumab and newer agents treat multiple conditions, reshaping treatment strategy.">異膚不只是皮膚病。AAD 2022 + 2026 共識整理出 5 大類共病:過敏(氣喘 / 食物 / 鼻炎 / EoE)、心理(憂鬱 / 焦慮 / 自殺意念)、骨骼(骨質疏鬆 / 骨折)、心血管(輕度上升)、皮膚感染(金黃色葡萄球菌 / eczema herpeticum)。Dupilumab 等新藥同時治多病、改變了治療策略。</span></div>

<h2 id="atopic" data-zh="一、過敏共病(atopic march)— 證據最強" data-en="1. Atopic comorbidities (atopic march) — strongest evidence">一、過敏共病(atopic march)— 證據最強</h2>

<h3 data-zh="氣喘 Asthma" data-en="Asthma">氣喘 Asthma</h3><ul><li data-zh="<strong>盛行率</strong>:成人異膚患者中氣喘 24.8%(95% CI 22.2-27.5%);整體比一般人高 3 倍" data-en="<strong>Prevalence</strong>: 24.8% (95% CI 22.2–27.5%) in adults with AD; 3× higher than general population"><strong>盛行率</strong>:成人異膚患者中氣喘 24.8%(95% CI 22.2-27.5%);整體比一般人高 3 倍</li><li data-zh="<strong>嚴重度相關</strong>:重度 AD vs 一般 RR 2.38;中度 1.94;輕度 1.34" data-en="<strong>Severity gradient</strong>: severe AD vs general RR 2.38; moderate 1.94; mild 1.34"><strong>嚴重度相關</strong>:重度 AD vs 一般 RR 2.38;中度 1.94;輕度 1.34</li><li data-zh="<strong>臨床意義</strong>:7-13 歲合併氣喘預示 AD 持續到成年的可能性高" data-en="<strong>Clinical significance</strong>: asthma at age 7–13 predicts persistence of AD into adulthood"><strong>臨床意義</strong>:7-13 歲合併氣喘預示 AD 持續到成年的可能性高</li><li data-zh="<strong>治療策略</strong>:Dupilumab 同時核可中重度氣喘 — 一藥治雙病" data-en="<strong>Treatment strategy</strong>: dupilumab is approved for moderate-severe asthma simultaneously — one drug, both conditions"><strong>治療策略</strong>:Dupilumab 同時核可中重度氣喘 — 一藥治雙病</li></ul>

<h3 data-zh="食物過敏 Food Allergy" data-en="Food allergy">食物過敏 Food Allergy</h3><ul><li data-zh="<strong>盛行率</strong>:成人 AD 食物過敏 11%(95% CI 6-16%);兒童更高(尤其嬰兒期重度 AD)" data-en="<strong>Prevalence</strong>: 11% (95% CI 6–16%) in adults with AD; higher in children (especially severe infantile AD)"><strong>盛行率</strong>:成人 AD 食物過敏 11%(95% CI 6-16%);兒童更高(尤其嬰兒期重度 AD)</li><li data-zh="<strong>嚴重度相關</strong>:重度 AD 食物過敏 RR 8.49(輕度 1.48,中度 2.40)" data-en="<strong>Severity gradient</strong>: severe AD food allergy RR 8.49 (mild 1.48, moderate 2.40)"><strong>嚴重度相關</strong>:重度 AD 食物過敏 RR 8.49(輕度 1.48,中度 2.40)</li><li data-zh="<strong>提醒</strong>:食物過敏陽性 ≠ 異膚誘發因子。盲目避食會造成兒童營養不良" data-en="<strong>Caution</strong>: positive food allergy testing ≠ AD trigger. Indiscriminate avoidance causes pediatric malnutrition"><strong>提醒</strong>:食物過敏陽性 ≠ 異膚誘發因子。盲目避食會造成兒童營養不良</li><li data-zh="<strong>檢測時機</strong>:嬰兒期重度 AD 合併多次明確過敏反應(蕁麻疹/呼吸困難於進食後 30-120 分鐘)時才檢測" data-en="<strong>Testing indications</strong>: infantile severe AD with repeated clear-cut allergic reactions (urticaria / respiratory distress within 30–120 min of ingestion)"><strong>檢測時機</strong>:嬰兒期重度 AD 合併多次明確過敏反應(蕁麻疹/呼吸困難於進食後 30-120 分鐘)時才檢測</li></ul>

<h3 data-zh="過敏性鼻炎 / 過敏性結膜炎 / 嗜酸性食道炎(EoE)" data-en="Allergic rhinitis / conjunctivitis / EoE">過敏性鼻炎 / 過敏性結膜炎 / 嗜酸性食道炎(EoE)</h3><ul><li data-zh="<strong>過敏性鼻炎</strong>:確定相關。嚴重 AD 風險顯著上升" data-en="<strong>Allergic rhinitis</strong>: clear association. Risk significantly elevated in severe AD"><strong>過敏性鼻炎</strong>:確定相關。嚴重 AD 風險顯著上升</li><li data-zh="<strong>結膜炎</strong>:Dupilumab 也可能加重結膜炎(需鑑別 dupi-conjunctivitis)" data-en="<strong>Conjunctivitis</strong>: dupilumab may also worsen conjunctivitis (need to differentiate dupi-conjunctivitis)"><strong>結膜炎</strong>:Dupilumab 也可能加重結膜炎(需鑑別 dupi-conjunctivitis)</li><li data-zh="<strong>EoE 嗜酸性食道炎</strong>:雙向相關;Dupilumab 同時核可 EoE 治療" data-en="<strong>EoE (eosinophilic esophagitis)</strong>: bidirectional association; dupilumab also approved for EoE"><strong>EoE 嗜酸性食道炎</strong>:雙向相關;Dupilumab 同時核可 EoE 治療</li><li data-zh="<strong>篩檢警訊</strong>:吞嚥困難、食物卡住感、年輕成人胃食道反流 → 轉介腸胃科內視鏡 + 切片" data-en="<strong>Screening red flags</strong>: dysphagia, food impaction sensation, GERD in young adult → refer GI for endoscopy + biopsy"><strong>篩檢警訊</strong>:吞嚥困難、食物卡住感、年輕成人胃食道反流 → 轉介腸胃科內視鏡 + 切片</li></ul>

<h2 id="immune" data-zh="二、免疫媒介共病" data-en="2. Immune-mediated comorbidities">二、免疫媒介共病</h2><ul><li data-zh="<strong>圓禿(Alopecia areata, AA)</strong>:確定相關;同時治療選項 — Baricitinib(已核可 AA)、Ritlecitinib(AA)" data-en="<strong>Alopecia areata (AA)</strong>: clear association; concurrent treatment options — baricitinib (AA-approved), ritlecitinib (AA)"><strong>圓禿(Alopecia areata, AA)</strong>:確定相關;同時治療選項 — Baricitinib(已核可 AA)、Ritlecitinib(AA)</li><li data-zh="<strong>慢性自發性蕁麻疹(CSU)</strong>:相關;Dupilumab 對部分 CSU 有效(off-label)" data-en="<strong>Chronic spontaneous urticaria (CSU)</strong>: associated; dupilumab effective in some CSU (off-label)"><strong>慢性自發性蕁麻疹(CSU)</strong>:相關;Dupilumab 對部分 CSU 有效(off-label)</li><li data-zh="<strong>白斑、發炎性腸道疾病(IBD)、類風濕性關節炎</strong>:Sidbury 2026 兒童共識:可能相關但證據強度較低" data-en="<strong>Vitiligo, IBD, RA</strong>: Sidbury 2026 pediatric consensus — possibly associated but lower evidence quality"><strong>白斑、發炎性腸道疾病(IBD)、類風濕性關節炎</strong>:Sidbury 2026 兒童共識:可能相關但證據強度較低</li></ul>

<h2 id="mental" data-zh="三、心理健康 — 臨床上最被低估" data-en="3. Mental health — the most clinically underestimated">三、心理健康 — 臨床上最被低估</h2><ul><li data-zh="<strong>憂鬱症</strong>:成人 AD 憂鬱症盛行率 ~25%(嚴重 AD 高達 40%);RR 1.5-2.5(嚴重度依存性)" data-en="<strong>Depression</strong>: ~25% prevalence in adults with AD (up to 40% in severe AD); RR 1.5–2.5 (severity-dependent)"><strong>憂鬱症</strong>:成人 AD 憂鬱症盛行率 ~25%(嚴重 AD 高達 40%);RR 1.5-2.5(嚴重度依存性)</li><li data-zh="<strong>焦慮</strong>:相關。慢性癢、外觀困擾、睡眠剝奪是核心驅動" data-en="<strong>Anxiety</strong>: associated. Chronic itch, appearance distress, sleep deprivation are core drivers"><strong>焦慮</strong>:相關。慢性癢、外觀困擾、睡眠剝奪是核心驅動</li><li data-zh="<strong>自殺意念</strong>:中重度 AD 自殺意念風險上升(青少年尤其);Dupilumab/JAK 改善睡眠後自殺意念顯著降低" data-en="<strong>Suicidal ideation</strong>: increased risk in moderate-severe AD (especially adolescents); ideation drops significantly after dupilumab/JAK improves sleep"><strong>自殺意念</strong>:中重度 AD 自殺意念風險上升(青少年尤其);Dupilumab/JAK 改善睡眠後自殺意念顯著降低</li><li data-zh="<strong>注意力不足過動症(ADHD)</strong>:可能相關;與夜間癢造成的睡眠剝奪有關" data-en="<strong>ADHD</strong>: possibly associated; linked to sleep deprivation from nocturnal itch"><strong>注意力不足過動症(ADHD)</strong>:可能相關;與夜間癢造成的睡眠剝奪有關</li><li data-zh="<strong>自閉症光譜</strong>:無確定相關(可能 confounding)" data-en="<strong>Autism spectrum</strong>: inconclusive (possible confounding)"><strong>自閉症光譜</strong>:無確定相關(可能 confounding)</li><li data-zh="<strong>篩檢工具</strong>:PHQ-9(憂鬱)、GAD-7(焦慮)、PSS(壓力)、PSQI(睡眠);中重度建議基線 + 治療 3 個月後再評估" data-en="<strong>Screening tools</strong>: PHQ-9 (depression), GAD-7 (anxiety), PSS (stress), PSQI (sleep); recommend baseline + 3-month-post-treatment in moderate-severe AD"><strong>篩檢工具</strong>:PHQ-9(憂鬱)、GAD-7(焦慮)、PSS(壓力)、PSQI(睡眠);中重度建議基線 + 治療 3 個月後再評估</li></ul>

<h2 id="substance" data-zh="四、物質使用" data-en="4. Substance use">四、物質使用</h2><ul><li data-zh="<strong>酒精使用障礙</strong>:可能相關。慢性疾病壓力 + 睡眠剝奪 + 心理共病" data-en="<strong>Alcohol use disorder</strong>: possibly associated. Chronic disease stress + sleep deprivation + psychiatric comorbidity"><strong>酒精使用障礙</strong>:可能相關。慢性疾病壓力 + 睡眠剝奪 + 心理共病</li><li data-zh="<strong>香菸</strong>:有相關。AD + 抽菸 → JAK 使用要更謹慎(MACE 風險)" data-en="<strong>Smoking</strong>: associated. AD + smoking → use JAK with extra caution (MACE risk)"><strong>香菸</strong>:有相關。AD + 抽菸 → JAK 使用要更謹慎(MACE 風險)</li></ul>

<h2 id="cv" data-zh="五、心血管疾病 — 證據相對薄弱但要注意" data-en="5. Cardiovascular disease — evidence relatively weak but worth noting">五、心血管疾病 — 證據相對薄弱但要注意</h2><ul><li data-zh="<strong>整體</strong>:輕度上升,但絕對風險增加不大" data-en="<strong>Overall</strong>: mildly increased risk, but absolute risk increment is small"><strong>整體</strong>:輕度上升,但絕對風險增加不大</li><li data-zh="<strong>高血壓</strong>:相關。重度 AD 全身性發炎影響血管" data-en="<strong>Hypertension</strong>: associated. Systemic inflammation in severe AD affects vasculature"><strong>高血壓</strong>:相關。重度 AD 全身性發炎影響血管</li><li data-zh="<strong>冠狀動脈疾病、周邊動脈疾病</strong>:可能相關" data-en="<strong>CAD, PAD</strong>: possibly associated"><strong>冠狀動脈疾病、周邊動脈疾病</strong>:可能相關</li><li data-zh="<strong>心肌梗塞、中風、心血管死亡</strong>:無確定相關" data-en="<strong>MI, stroke, CV death</strong>: inconclusive"><strong>心肌梗塞、中風、心血管死亡</strong>:無確定相關</li><li data-zh="<strong>靜脈栓塞</strong>:重度 AD 風險上升(可能與全身性發炎相關)— JAK 使用須評估 VTE 史" data-en="<strong>VTE</strong>: increased risk in severe AD (possibly inflammation-related) — assess VTE history before JAK"><strong>靜脈栓塞</strong>:重度 AD 風險上升(可能與全身性發炎相關)— JAK 使用須評估 VTE 史</li></ul>

<h2 id="metabolic" data-zh="六、代謝疾病" data-en="6. Metabolic disorders">六、代謝疾病</h2><ul><li data-zh="<strong>糖尿病、血脂異常、肥胖</strong>:可能相關。長期口服類固醇使用是混淆因素" data-en="<strong>Diabetes, dyslipidemia, obesity</strong>: possibly associated. Long-term oral steroid use is a confounder"><strong>糖尿病、血脂異常、肥胖</strong>:可能相關。長期口服類固醇使用是混淆因素</li><li data-zh="<strong>代謝症候群整體</strong>:無確定相關" data-en="<strong>Metabolic syndrome overall</strong>: inconclusive"><strong>代謝症候群整體</strong>:無確定相關</li><li data-zh="<strong>提醒</strong>:JAK 使用會升高血脂,需基線 + 3 個月追蹤" data-en="<strong>Note</strong>: JAK inhibitors elevate lipids; baseline + 3-month follow-up monitoring required"><strong>提醒</strong>:JAK 使用會升高血脂,需基線 + 3 個月追蹤</li></ul>

<h2 id="bone" data-zh="七、骨骼健康" data-en="7. Bone health">七、骨骼健康</h2><ul><li data-zh="<strong>骨質疏鬆</strong>:相關。可能與長期口服類固醇 + 慢性發炎有關" data-en="<strong>Osteoporosis</strong>: associated. Likely related to long-term oral steroid + chronic inflammation"><strong>骨質疏鬆</strong>:相關。可能與長期口服類固醇 + 慢性發炎有關</li><li data-zh="<strong>骨折風險</strong>:相關。重度 AD 有顯著上升" data-en="<strong>Fracture risk</strong>: associated. Significant increase in severe AD"><strong>骨折風險</strong>:相關。重度 AD 有顯著上升</li><li data-zh="<strong>實務</strong>:長期 (>3 個月) 全身類固醇治療者 → 鈣 + 維他命 D 補充、考慮 DXA 掃描" data-en="<strong>Practical</strong>: patients on long-term (&gt; 3 months) systemic steroids → calcium + vitamin D, consider DXA scan"><strong>實務</strong>:長期 (&gt; 3 個月) 全身類固醇治療者 → 鈣 + 維他命 D 補充、考慮 DXA 掃描</li></ul>

<h2 id="infection" data-zh="八、皮膚感染 — 必須積極處理" data-en="8. Skin infection — actively manage">八、皮膚感染 — 必須積極處理</h2><ul><li data-zh="<strong>金黃色葡萄球菌定植</strong>:90%+ 異膚患者皮膚帶菌(vs 一般人 5-30%)。是發炎惡化關鍵驅動因子之一" data-en="<strong>S aureus colonization</strong>: 90%+ AD patients colonized (vs general 5–30%). Key driver of inflammation flare"><strong>金黃色葡萄球菌定植</strong>:90%+ 異膚患者皮膚帶菌(vs 一般人 5-30%)。是發炎惡化關鍵驅動因子之一</li><li data-zh="<strong>蜂窩性組織炎、膿皰瘡</strong>:發生率比一般人高 2-3 倍" data-en="<strong>Cellulitis, impetigo</strong>: 2–3× higher incidence than general population"><strong>蜂窩性組織炎、膿皰瘡</strong>:發生率比一般人高 2-3 倍</li><li data-zh="<strong>Eczema herpeticum(疱疹性濕疹)</strong>:急症!全身發燒 + 皮膚成群水泡 / 膿皰 → 立即口服 / 靜脈 acyclovir" data-en="<strong>Eczema herpeticum</strong>: emergency! Systemic fever + grouped vesicles/pustules → immediate oral or IV acyclovir"><strong>Eczema herpeticum(疱疹性濕疹)</strong>:急症!全身發燒 + 皮膚成群水泡 / 膿皰 → 立即口服 / 靜脈 acyclovir</li><li data-zh="<strong>鬚瘡傳染性軟疣</strong>:好發於異膚兒童;通常自限性,合併 AD 控制不佳時擴散更廣" data-en="<strong>Molluscum contagiosum</strong>: more frequent in pediatric AD; typically self-limited; spreads more widely with poor AD control"><strong>鬚瘡傳染性軟疣</strong>:好發於異膚兒童;通常自限性,合併 AD 控制不佳時擴散更廣</li><li data-zh="<strong>漂白水泡澡</strong>:稀釋 0.005% NaClO(0.5 杯漂白水 / 全浴缸)、每週 2 次,有助降低 S aureus 負擔(Sidbury 2023 conditional FOR)" data-en="<strong>Bleach baths</strong>: dilute 0.005% NaClO (0.5 cup bleach / full bathtub) twice weekly reduces S aureus burden (Sidbury 2023 conditional FOR)"><strong>漂白水泡澡</strong>:稀釋 0.005% NaClO(0.5 杯漂白水 / 全浴缸)、每週 2 次,有助降低 S aureus 負擔(Sidbury 2023 conditional FOR)</li></ul>

<h2 id="ped-prevention" data-zh="九、兒童異膚的初級預防(Sidbury 2026 兒童共識)" data-en="9. Primary prevention in pediatric AD (Sidbury 2026 pediatric consensus)">九、兒童異膚的初級預防(Sidbury 2026 兒童共識)</h2><ul><li data-zh="<strong>母乳哺餵</strong>:母乳餵 ≥ 4 個月可能降低異膚風險(conditional FOR)" data-en="<strong>Breastfeeding</strong>: breastfeeding ≥ 4 months may reduce AD risk (conditional FOR)"><strong>母乳哺餵</strong>:母乳餵 ≥ 4 個月可能降低異膚風險(conditional FOR)</li><li data-zh="<strong>水解配方奶粉</strong>:目前證據不支持高風險嬰兒常規使用(無顯著預防效果)" data-en="<strong>Hydrolyzed formula</strong>: current evidence does not support routine use in high-risk infants (no significant preventive effect)"><strong>水解配方奶粉</strong>:目前證據不支持高風險嬰兒常規使用(無顯著預防效果)</li><li data-zh="<strong>益生菌(probiotics)</strong>:孕期 + 哺乳期母親使用可能有益(conditional);兒童單獨使用證據不足" data-en="<strong>Probiotics</strong>: maternal use during pregnancy + lactation may help (conditional); insufficient evidence for child-only use"><strong>益生菌(probiotics)</strong>:孕期 + 哺乳期母親使用可能有益(conditional);兒童單獨使用證據不足</li><li data-zh="<strong>嬰兒早期保濕</strong>:過去認為可預防,新研究(BEEP / PreventADALL)結果不一致 — 不再強烈建議" data-en="<strong>Early-life emollient</strong>: previously considered preventive; new trials (BEEP, PreventADALL) inconsistent — no longer strongly recommended"><strong>嬰兒早期保濕</strong>:過去認為可預防,新研究(BEEP / PreventADALL)結果不一致 — 不再強烈建議</li><li data-zh="<strong>過敏食物</strong>:LEAP 試驗 — 高風險嬰兒早期(4-11 個月)引入花生可預防花生過敏" data-en="<strong>Allergenic foods</strong>: LEAP trial — early peanut introduction (4–11 months) in high-risk infants prevents peanut allergy"><strong>過敏食物</strong>:LEAP 試驗 — 高風險嬰兒早期(4-11 個月)引入花生可預防花生過敏</li></ul>

<h2 id="screening-table" data-zh="十、實務篩檢清單(中重度 AD 病人)" data-en="10. Practical screening checklist (moderate-severe AD)">十、實務篩檢清單(中重度 AD 病人)</h2><table style="width:100%;border-collapse:collapse;font-size:13.5px;margin:14px 0"><thead><tr style="background:#ebe4d8"><th style="padding:8px;border:1px solid #dcd5c8;text-align:left" data-zh="共病類別" data-en="Domain">共病類別</th><th style="padding:8px;border:1px solid #dcd5c8" data-zh="篩檢項目 / 工具" data-en="Screening / tool">篩檢項目 / 工具</th><th style="padding:8px;border:1px solid #dcd5c8" data-zh="頻率" data-en="Frequency">頻率</th></tr></thead><tbody><tr><td style="padding:8px;border:1px solid #dcd5c8" data-zh="過敏" data-en="Atopic">過敏</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="氣喘症狀問診、過敏鼻炎、吞嚥困難 / 食物卡住感(EoE)" data-en="Asthma symptoms, allergic rhinitis, dysphagia / food impaction (EoE)">氣喘症狀問診、過敏鼻炎、吞嚥困難 / 食物卡住感(EoE)</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="基線 + 每年 1 次" data-en="Baseline + annual">基線 + 每年 1 次</td></tr><tr><td style="padding:8px;border:1px solid #dcd5c8" data-zh="心理健康" data-en="Mental health">心理健康</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="PHQ-9 + GAD-7 + PSQI(睡眠)" data-en="PHQ-9 + GAD-7 + PSQI (sleep)">PHQ-9 + GAD-7 + PSQI(睡眠)</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="基線 + 治療 3 個月後 + 每年" data-en="Baseline + 3-month post-treatment + annual">基線 + 治療 3 個月後 + 每年</td></tr><tr><td style="padding:8px;border:1px solid #dcd5c8" data-zh="心血管 / 代謝" data-en="CV / metabolic">心血管 / 代謝</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="血壓、空腹血糖、血脂(JAK 用藥前必查)" data-en="BP, fasting glucose, lipid panel (mandatory pre-JAK)">血壓、空腹血糖、血脂(JAK 用藥前必查)</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="基線 + JAK 用藥 3 個月後" data-en="Baseline + 3 months on JAK">基線 + JAK 用藥 3 個月後</td></tr><tr><td style="padding:8px;border:1px solid #dcd5c8" data-zh="骨骼" data-en="Bone">骨骼</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="長期口服類固醇(>3 個月)→ DXA + 鈣 / 維他命 D" data-en="Long-term oral steroid (&gt; 3 months) → DXA + calcium/vitamin D">長期口服類固醇(&gt;3 個月)→ DXA + 鈣 / 維他命 D</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="長期類固醇治療開始時" data-en="At start of long-term steroid therapy">長期類固醇治療開始時</td></tr><tr><td style="padding:8px;border:1px solid #dcd5c8" data-zh="感染" data-en="Infection">感染</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="S aureus 拭子(難治者)、單純疱疹病史(eczema herpeticum 預警)" data-en="S aureus swab (refractory cases), HSV history (eczema herpeticum warning)">S aureus 拭子(難治者)、單純疱疹病史(eczema herpeticum 預警)</td><td style="padding:8px;border:1px solid #dcd5c8" data-zh="急性發作惡化時" data-en="At acute worsening">急性發作惡化時</td></tr></tbody></table>

<h2 id="references" data-zh="參考資料" data-en="References">參考資料</h2><ol style="font-size:13px;line-height:1.8"><li>Davis DMR, Drucker AM, Alikhan A, et al. <em>American Academy of Dermatology Guidelines: Awareness of comorbidities associated with atopic dermatitis in adults.</em> J Am Acad Dermatol. 2022;86:1336.e1-e18. <a href="https://doi.org/10.1016/j.jaad.2022.01.009" target="_blank" rel="noopener">DOI</a></li><li>Sidbury R, Alikhan A, Bercovitch L, et al. <em>Guidelines of care for the primary prevention of atopic dermatitis and awareness of comorbid conditions in pediatric atopic dermatitis.</em> J Am Acad Dermatol. 2026;in press.</li><li>Du Toit G, Roberts G, Sayre PH, et al. <em>Randomized trial of peanut consumption in infants at risk for peanut allergy (LEAP).</em> N Engl J Med. 2015;372:803-813.</li><li>Chalmers JR, Haines RH, Bradshaw LE, et al. <em>Daily emollient during infancy for prevention of eczema: the BEEP randomised controlled trial.</em> Lancet. 2020;395:962-972.</li><li>Sidbury R, Alikhan A, Bercovitch L, et al. <em>Guidelines of care for the management of atopic dermatitis in adults with topical therapies.</em> J Am Acad Dermatol. 2023;89:e1-e20.</li></ol></article>'''

s = re.sub(r'<article[^>]*data-slug="eczema-myths"[\s\S]*?</article>', ART, s, count=1)

with open(P, 'w', encoding='utf-8') as f:
    f.write(s)
print(f'Wrote AD comorbidity article: {len(s)} bytes')
