"""Record all immutable generated bytes before final physician approval.

This offline preparatory artifact is NOT a publication receipt. It neither runs
generators nor approves their output, queries live author intent, modifies Git,
or replaces the existing delivery gates. The API, final approval request and
publication stages must explicitly adopt this contract before it can be used.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path, PurePosixPath
import subprocess
import urllib.error

from _cms_delivery import FILE, REPO, ImmutableBlobs, approved_sources, parse, receipts, slug_for
from _prepare_article_candidate import git, read_blob, revision
from _validate_article_request import request_record

MAX_FILES = 10_000
MAX_BLOB = 50_000_000
MAX_TOTAL = 256_000_000
MAX_MANIFEST = 2_000_000
FIELDS = {'version', 'repository', 'file', 'pipelineHead', 'sourceHead',
          'generatedHead', 'generatedTreeSha', 'sourceEvidence', 'files',
          'state', 'generationVerified', 'contentApproved', 'ciVerified', 'published'}


def run(root: Path, *args: str, data: bytes | None = None) -> bytes:
    return subprocess.run(['git', *args], cwd=root, input=data, capture_output=True,
                          check=True, timeout=60).stdout


def commit(root: Path, sha: str) -> tuple[str, list[str]]:
    sha = revision(sha)
    # A hex ID can identify any Git object; require the object itself to be a
    # commit instead of accepting a peeled tag or silently coercing a tree.
    if run(root, 'cat-file', '-t', sha).strip() != b'commit':
        raise ValueError('Package identity must be a commit')
    raw = run(root, 'cat-file', 'commit', sha)
    headers = raw.split(b'\n\n', 1)[0].splitlines()
    trees = [line[5:].decode('ascii') for line in headers if line.startswith(b'tree ')]
    parents = [revision(line[7:].decode('ascii')) for line in headers if line.startswith(b'parent ')]
    if len(trees) != 1:
        raise ValueError('Package commit has an ambiguous tree')
    return revision(trees[0]), parents


def entries(root: Path, tree: str) -> dict[str, dict]:
    tree = revision(tree)
    if run(root, 'cat-file', '-t', tree).strip() != b'tree':
        raise ValueError('Package inventory requires an exact Git tree')
    rows = run(root, 'ls-tree', '-r', '-z', '--full-tree', tree).split(b'\0')
    result = {}
    for row in rows:
        if not row:
            continue
        header, path_raw = row.split(b'\t', 1)
        mode, kind, blob = header.decode('ascii').split()
        path = path_raw.decode('utf-8')
        # The complete tree includes an unchanged executable pre-push hook.
        # Links/submodules are never regular content and cannot be archived as
        # a digest of the bytes they point to.
        if kind != 'blob' or mode not in {'100644', '100755'}:
            raise ValueError('Package tree contains a link or non-ordinary object')
        parsed = PurePosixPath(path)
        if (not path or path.startswith('/') or '\\' in path or ':' in path or
                any(ord(char) < 32 or ord(char) == 127 for char in path) or
                any(part in {'', '.', '..'} for part in path.split('/')) or
                parsed.as_posix() != path or path in result):
            raise ValueError('Package file path is ambiguous')
        result[path] = {'mode': mode, 'blobSha': revision(blob)}
        if len(result) > MAX_FILES:
            raise ValueError('Package file inventory exceeds its bound')
    return dict(sorted(result.items()))


class GitEvidence:
    """Immutable local objects only; never represents current remote intent."""
    def __init__(self, root: Path):
        self.root = root

    def get(self, path: str):
        if path.startswith('/contents/'):
            name, separator, sha = path[len('/contents/'):].partition('?ref=')
            if not separator:
                raise ValueError('Missing immutable content identity')
            value = read_blob(self.root, revision(sha), name, optional=True)
            if value is None:
                raise urllib.error.HTTPError('local-git-object', 404, 'Missing immutable blob', {}, None)
            blob, raw = value
            return {'type': 'file', 'path': name, 'sha': blob, 'size': len(raw),
                    'encoding': 'base64', 'content': base64.b64encode(raw).decode('ascii')}
        if path.startswith('/git/commits/'):
            sha = revision(path[len('/git/commits/'):])
            tree, parents = commit(self.root, sha)
            return {'sha': sha, 'tree': {'sha': tree}, 'parents': [{'sha': parent} for parent in parents]}
        if path.startswith('/git/trees/') and path.endswith('?recursive=1'):
            tree = revision(path[len('/git/trees/'):-len('?recursive=1')])
            return {'sha': tree, 'truncated': False, 'tree': [
                {'path': name, 'mode': entry['mode'], 'type': 'blob', 'sha': entry['blobSha']}
                for name, entry in entries(self.root, tree).items()]}
        if path.startswith('/compare/'):
            base, head = path[len('/compare/'):].split('...')
            base, head = revision(base), revision(head)
            result = subprocess.run(['git', 'merge-base', '--is-ancestor', base, head],
                                    cwd=self.root, capture_output=True, timeout=20)
            if result.returncode not in {0, 1}:
                raise subprocess.CalledProcessError(result.returncode, result.args)
            return {'status': 'identical' if base == head else 'ahead' if result.returncode == 0 else 'diverged',
                    'merge_base_commit': {'sha': base if result.returncode == 0 else None}}
        raise ValueError('Unsupported immutable package evidence query')


def approved_source(root: Path, source_head: str, file: str, *, now=None) -> dict:
    _, raw = read_blob(root, source_head, FILE)
    matches = [proof for proof in receipts(raw, now=now) if proof['file'] == file]
    if len(matches) != 1 or matches[0]['action'] == 'unpublish':
        raise ValueError('Package requires one source publication request')
    proof = matches[0]
    pipeline = proof['preparedAgainst']
    _, parents = commit(root, source_head)
    if parents != [pipeline]:
        raise ValueError('Source preparation is not a direct child of its pipeline')
    request_path = '.cms-requests/' + slug_for(file) + '.json'
    blob, request_raw = read_blob(root, proof['requestHead'], request_path)
    record = request_record(request_raw, file, now=now)
    expected = {'version': 1, 'file': file, 'action': proof['action'],
                'draftHead': proof['draftHead'], 'manifestSha': proof['manifestSha'],
                'blobSha': proof['articleBlobSha'], 'baseSha': proof['baseSha'],
                'approvedBy': proof['approvedBy'], 'contentApproved': True,
                'requestedAt': proof['requestedAt'], 'scheduledAt': proof['scheduledAt']}
    _, request_parents = commit(root, proof['requestHead'])
    changed = run(root, 'diff-tree', '--no-commit-id', '--name-only', '-r', '-z',
                  proof['draftHead'], proof['requestHead']).split(b'\0')
    if (blob != proof['requestBlobSha'] or record != expected or
            request_parents != [proof['draftHead']] or
            [name for name in changed if name] != [request_path.encode('utf8')]):
        raise ValueError('Package source does not bind the immutable author request')
    approved_sources(ImmutableBlobs(GitEvidence(root)), proof)
    paths = run(root, 'diff', '--name-only', '-z', pipeline, source_head).split(b'\0')
    actual = {name.decode('utf8') for name in paths if name}
    if FILE not in actual or not actual <= set(proof['sourceSha256']) | {FILE}:
        raise ValueError('Source preparation changed unrelated files')
    for name, digest in proof['sourceSha256'].items():
        if hashlib.sha256(read_blob(root, source_head, name)[1]).hexdigest() != digest:
            raise ValueError('Source preparation differs from the approved input')
    return proof


def inventory(root: Path, generated_tree: str) -> dict[str, dict]:
    files = entries(root, generated_tree)
    blobs = list(dict.fromkeys(entry['blobSha'] for entry in files.values()))
    request = ''.join(blob + '\n' for blob in blobs).encode('ascii')
    sizes = {}
    checked = run(root, 'cat-file', '--batch-check=%(objectname) %(objecttype) %(objectsize)', data=request)
    lines = checked.splitlines()
    if len(lines) != len(blobs):
        raise ValueError('Incomplete package object inventory')
    for blob, line in zip(blobs, lines):
        identity, kind, length = line.decode('ascii').split()
        if identity != blob or kind != 'blob' or not length.isdigit() or int(length) > MAX_BLOB:
            raise ValueError('Package blob exceeds its bound or has a different identity')
        sizes[blob] = int(length)
    # Count every output path, even when Git deduplicates identical blobs. An
    # archive/export eventually materializes each file separately.
    if sum(sizes[entry['blobSha']] for entry in files.values()) > MAX_TOTAL:
        raise ValueError('Package bytes exceed their bound')
    payload = run(root, 'cat-file', '--batch', data=request)
    offset = 0
    hashes = {}
    for blob in blobs:
        end = payload.index(b'\n', offset)
        if payload[offset:end] != (blob + ' blob ' + str(sizes[blob])).encode('ascii'):
            raise ValueError('Package object transport identity differs')
        start = end + 1
        raw = payload[start:start + sizes[blob]]
        offset = start + sizes[blob]
        if len(raw) != sizes[blob] or payload[offset:offset+1] != b'\n':
            raise ValueError('Package object transport is truncated')
        offset += 1
        if hashlib.sha1(b'blob ' + str(len(raw)).encode('ascii') + b'\0' + raw).hexdigest() != blob:
            raise ValueError('Package blob content does not match Git identity')
        hashes[blob] = hashlib.sha256(raw).hexdigest()
    if offset != len(payload):
        raise ValueError('Package object transport has trailing bytes')
    return {name: {**entry, 'size': sizes[entry['blobSha']], 'sha256': hashes[entry['blobSha']]}
            for name, entry in files.items()}


def create(root: Path, source_head: str, generated_head: str, file: str, *, now=None) -> dict:
    root = root.resolve()
    source_head, generated_head = revision(source_head), revision(generated_head)
    slug = slug_for(file)
    proof = approved_source(root, source_head, file, now=now)
    tree, parents = commit(root, generated_head)
    if parents != [source_head]:
        raise ValueError('Generated package must be a direct child of the source preparation')
    source_tree, _ = commit(root, source_head)
    before, after = entries(root, source_tree), entries(root, tree)
    article_paths = (file, 'en/blog/' + slug + '.html')
    if any(name not in after or after[name]['mode'] != '100644' for name in article_paths):
        raise ValueError('Package is missing its Chinese or English article')
    if read_blob(root, generated_head, FILE) != read_blob(root, source_head, FILE):
        raise ValueError('Generation changed the source approval receipt')
    for name, entry in after.items():
        if entry['mode'] == '100755' and before.get(name) != entry:
            raise ValueError('Generation introduced or changed an executable file')
    value = {'version': 1, 'repository': REPO, 'file': file,
             'pipelineHead': proof['preparedAgainst'], 'sourceHead': source_head,
             'generatedHead': generated_head, 'generatedTreeSha': tree,
             'sourceEvidence': proof, 'files': inventory(root, tree),
             'state': 'generated_package_recorded', 'generationVerified': False,
             'contentApproved': False, 'ciVerified': False, 'published': False}
    if len(encode(value)) > MAX_MANIFEST:
        raise ValueError('Package manifest exceeds its bound')
    return value


def encode(value: dict) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + '\n').encode('utf8')


def verify(root: Path, raw: bytes, *, now=None) -> dict:
    value = parse(raw, canonical=True, limit=MAX_MANIFEST)
    if (not isinstance(value, dict) or set(value) != FIELDS or
            type(value['version']) is not int or value['version'] != 1 or
            value['repository'] != REPO or value['state'] != 'generated_package_recorded' or
            any(type(value[key]) is not bool or value[key] for key in
                ('generationVerified', 'contentApproved', 'ciVerified', 'published'))):
        raise ValueError('Invalid preparatory package contract')
    expected = create(root, value['sourceHead'], value['generatedHead'], value['file'], now=now)
    if raw != encode(expected):
        raise ValueError('Package manifest differs from its complete immutable inputs or outputs')
    return {'generatedHead': value['generatedHead'], 'files': len(value['files']),
            'immutableIdentityVerified': True, 'liveAuthorIntentVerified': False,
            'generationVerified': False, 'contentApproved': False, 'ciVerified': False,
            'published': False}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parent)
    sub = parser.add_subparsers(dest='command', required=True)
    build = sub.add_parser('record')
    build.add_argument('--source-head', required=True)
    build.add_argument('--generated-head', required=True)
    build.add_argument('--file', required=True)
    check = sub.add_parser('verify')
    check.add_argument('manifest', type=Path)
    args = parser.parse_args()
    if args.command == 'record':
        print(encode(create(args.root, args.source_head, args.generated_head, args.file)).decode('utf8'), end='')
    else:
        # Bound before reading; the parser also checks the actual byte length.
        if args.manifest.stat().st_size > MAX_MANIFEST:
            raise ValueError('Package manifest exceeds its bound')
        print(json.dumps(verify(args.root, args.manifest.read_bytes()), ensure_ascii=True))


if __name__ == '__main__':
    main()
