#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Extract @media print rules from every page's inline <style> into a
single shared external stylesheet loaded with media="print".

Round 2-H from OPEN_SOURCE_INTEGRATIONS.md (pragmatic Python-only
alternative to beasties — no Node dependency required).

Why @media print is the right first cut:
  1. Identical across all 114 pages (~2 KB each → 228 KB of redundant
     inline weight site-wide before HTML compression).
  2. Browsers don't fetch `<link rel="stylesheet" media="print">`
     during normal page load — only when the user invokes Cmd+P /
     File→Print. So extraction = pure cold-load weight savings with
     ZERO render-blocking cost.
  3. Safe to extract: print rules never affect interactive painting,
     so we can move them out of the critical path entirely.

Idempotent: detects existing `<link ... media="print">` matching our
canonical href and skips. Strips `@media print { ... }` from inline
<style> blocks each run.
"""
from __future__ import annotations

import io
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent

try:
    sys.path.insert(0, str(ROOT))
    from _normalize_css_links import ASSET_VERSION as _ASSET_VERSION
except Exception:
    _ASSET_VERSION = "202605191900"

PRINT_CSS_PATH = ROOT / "assets" / "dn-print.css"
PRINT_LINK = (
    f'<link rel="stylesheet" media="print" '
    f'href="/assets/dn-print.css?v={_ASSET_VERSION}" '
    f'id="dn-print-css">'
)

# @media print { ... }  with balanced-brace matching
PRINT_MEDIA_RE = re.compile(
    r"@media\s+print\s*\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}",
    re.IGNORECASE,
)

# Detect existing dn-print-css link (for idempotency).
EXISTING_LINK_RE = re.compile(
    r'<link[^>]+id="dn-print-css"[^>]*>',
    re.IGNORECASE,
)

SKIP_NAMES = {"404.html", "offline.html", "reset-sw.html", "admin.html"}
SKIP_DIRS = {".git", "node_modules", "pagefind", "admin"}


def extract_from_file(path: Path, canonical_print_css: list[str]) -> int:
    """Extract @media print rules from inline <style> blocks.

    Returns number of rules extracted (0 if no change).
    canonical_print_css mutates — first-run rules get appended for
    later writing to the shared dn-print.css.
    """
    src = path.read_text(encoding="utf-8")
    extracted_count = 0
    new_src = src

    # Find every inline <style>...</style> block and strip @media print.
    def replace_style(m: re.Match) -> str:
        nonlocal extracted_count
        css = m.group(1)
        # Pull out @media print blocks
        chunks = []

        def collect(mm: re.Match) -> str:
            nonlocal extracted_count
            chunks.append(mm.group(0))
            extracted_count += 1
            return ""

        new_css = PRINT_MEDIA_RE.sub(collect, css)
        if chunks and not canonical_print_css:
            # First file we see: this is the canonical print CSS.
            # Subsequent files' chunks should be identical; we don't
            # write them out (they're already in canonical).
            canonical_print_css.extend(chunks)
        return m.group(0).replace(css, new_css)

    new_src = re.sub(
        r"<style\b[^>]*>([\s\S]*?)</style>",
        replace_style,
        new_src,
    )

    if extracted_count == 0:
        return 0

    # Inject the dn-print.css <link> if not already present.
    if not EXISTING_LINK_RE.search(new_src):
        head_close = new_src.find("</head>")
        if head_close != -1:
            new_src = new_src[:head_close] + PRINT_LINK + new_src[head_close:]

    if new_src != src:
        path.write_text(new_src, encoding="utf-8")
        return extracted_count
    return 0


def main() -> int:
    targets: list[Path] = []
    for fp in sorted(ROOT.rglob("*.html")):
        parts = fp.relative_to(ROOT).parts
        if any(p in SKIP_DIRS for p in parts):
            continue
        if fp.name in SKIP_NAMES:
            continue
        targets.append(fp)

    canonical_chunks: list[str] = []
    total_extracted = 0
    files_changed = 0

    for fp in targets:
        n = extract_from_file(fp, canonical_chunks)
        if n:
            total_extracted += n
            files_changed += 1

    # Write the shared print CSS (only if we collected canonical chunks)
    if canonical_chunks:
        PRINT_CSS_PATH.parent.mkdir(exist_ok=True)
        header = (
            "/* Auto-generated by _normalize_critical_css.py — DO NOT EDIT.\n"
            " * Print-only rules extracted from inline <style> blocks.\n"
            " * Loaded via <link rel=\"stylesheet\" media=\"print\"> so\n"
            " * browsers fetch only when the user actually prints.\n"
            " */\n"
        )
        body = "\n".join(canonical_chunks)
        PRINT_CSS_PATH.write_text(header + body + "\n", encoding="utf-8")

    print(f"[critical-css] extracted {total_extracted} @media print blocks "
          f"from {files_changed} pages; "
          f"wrote {PRINT_CSS_PATH.relative_to(ROOT).as_posix()} "
          f"({PRINT_CSS_PATH.stat().st_size if PRINT_CSS_PATH.exists() else 0} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
